project:
  outputs:
    dev:
      account: 'fya62509.us-east-1'
      database: spectra_dbt_dev_db
      password: Spectra@2022
      role: rl_dev_spectra_dbt
      schema: dev_curated
      threads: 1
      type: snowflake
      user: sunilm.kumar@lntinfotech.com
      warehouse: wh_dev_spectra_dbt
    prod:
      account: 'fya62509.us-east-1'
      database: spectra_dbt_dev_db
      password: Spectra@2023	
      role: rl_dev_spectra_dbt
      schema: dev_curated
      threads: 1
      type: snowflake
      user: spectra_dbt_dev_user
      warehouse: wh_dev_spectra_dbt
  target: prod
  