USE DATABASE DM_DB;

CREATE SCHEMA ICEBERG;

CREATE OR REPLACE EXTERNAL VOLUME S3_ICEBERG_STORE
   STORAGE_LOCATIONS =
      (
         (
            NAME = 'my-iceberg-datalake-us-west-oregon'
            STORAGE_PROVIDER = 'S3'
            STORAGE_BASE_URL = 's3://my-iceberg-datalake/storage/'
            STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::606300006141:role/snowflake_role'
         )
      );

DESC EXTERNAL VOLUME S3_ICEBERG_STORE;      


CREATE ICEBERG TABLE SAMPLE_TB (ID INTEGER, NAME VARCHAR)
EXTERNAL_VOLUME='S3_ICEBERG_STORE'
CATALOG='SNOWFLAKE'
BASE_LOCATION=''
;

DESCRIBE ICEBERG TABLE CUSOTMER;

INSERT INTO SAMPLE_TB
VALUES(1,'SAURABH');

CREATE OR REPLACE ICEBERG TABLE CUSOTMER
(
	C_CUSTOMER_SK NUMBER(38,0),
	C_CUSTOMER_ID string,
	C_CURRENT_CDEMO_SK NUMBER(38,0),
	C_CURRENT_HDEMO_SK NUMBER(38,0),
	C_CURRENT_ADDR_SK NUMBER(38,0),
	C_FIRST_SHIPTO_DATE_SK NUMBER(38,0),
	C_FIRST_SALES_DATE_SK NUMBER(38,0),
	C_SALUTATION string,
	C_FIRST_NAME string,
	C_LAST_NAME string,
	C_PREFERRED_CUST_FLAG string,
	C_BIRTH_DAY NUMBER(38,0),
	C_BIRTH_MONTH NUMBER(38,0),
	C_BIRTH_YEAR NUMBER(38,0),
	C_BIRTH_COUNTRY string,
	C_LOGIN string,
	C_EMAIL_ADDRESS string,
	C_LAST_REVIEW_DATE string
)
EXTERNAL_VOLUME='S3_ICEBERG_STORE'
CATALOG='SNOWFLAKE'
BASE_LOCATION=''
;

CREATE OR REPLACE ICEBERG TABLE DM_DB.ICEBERG.LINEITEM (
	L_ORDERKEY NUMBER(38,0),
	L_PARTKEY NUMBER(38,0),
	L_SUPPKEY NUMBER(38,0),
	L_LINENUMBER NUMBER(38,0),
	L_QUANTITY NUMBER(38,0),
	L_EXTENDEDPRICE NUMBER(38,0),
	L_DISCOUNT NUMBER(38,0),
	L_TAX NUMBER(38,0),
	L_RETURNFLAG string,
	L_LINESTATUS string,
	L_SHIPINSTRUCT string,
	L_SHIPMODE string,
	L_COMMENT string
)EXTERNAL_VOLUME='S3_ICEBERG_STORE'
CATALOG='SNOWFLAKE'
BASE_LOCATION='';

CREATE OR REPLACE ICEBERG TABLE DM_DB.ICEBERG.SALES_ORDER_2 (
	O_ORDERKEY NUMBER(38,0),
	O_CUSTKEY NUMBER(38,0),
	O_ORDERSTATUS STRING,
	O_TOTALPRICE NUMBER(38,0),
	O_ORDERDATE STRING,
	O_ORDERPRIORITY STRING,
	O_CLERK STRING,
	O_SHIPPRIORITY NUMBER(38,0),
	O_COMMENT STRING
)EXTERNAL_VOLUME='S3_ICEBERG_STORE'
CATALOG='SNOWFLAKE'
BASE_LOCATION='';


CREATE ICEBERG TABLE SAMPLE_TB (ID INTEGER, NAME VARCHAR)
EXTERNAL_VOLUME='S3_ICEBERG_STORE'
CATALOG='SNOWFLAKE'
BASE_LOCATION=''
;

DESCRIBE ICEBERG TABLE SAMPLE_TB;

INSERT INTO SAMPLE_TB
VALUES(2,'SPECTRA');


CREATE ICEBERG TABLE SAMPLE_TB_2 (ID INTEGER, NAME VARCHAR)
EXTERNAL_VOLUME='S3_ICEBERG_STORE'
CATALOG='SNOWFLAKE'
BASE_LOCATION='FOLDER_1/SAMPLE_DIR'
;

INSERT INTO SAMPLE_TB_2
VALUES(2,'SPECTRA');

SELECT * FROM SAMPLE_TB_2;

CREATE ICEBERG TABLE INVENTORY 
EXTERNAL_VOLUME='S3_ICEBERG_STORE'
CATALOG='SNOWFLAKE'
BASE_LOCATION='FOLDER_1/SAMPLE_DIR'
AS
SELECT * FROM CUSTOMER.PUBLIC.INVENTORY
WHERE SCHEMA_NAME='SFLIGHT';


SELECT * FROM INVENTORY;
